class Trait {
  constructor(name, cost, opposites, modifiers, allowedEthics) {
    this.name = name;
    this.cost = cost;
    this.opposites = opposites;
    this.modifiers = modifiers;
    this.allowedEthics = allowedEthics;
  }
}

var traitsList = ["agrarian", 
                  "thrifty", 
                  "industrious", 
                  "intelligent", 
                  "naturalEngineers", 
                  "naturalPhysicists", 
                  "naturalSociologists",
                  "extremelyAdaptive",
                  "adaptive",
                  "nonAdaptive",
                  "rapidBreeders",
                  "slowBreeders",
                  "talented",
                  "quickLearners",
                  "slowLearners",
                  "veryStrong",
                  "strong",
                  "weak",
                  "nomadic",
                  "sedentary",
                  "communal",
                  "solitary",
                  "charismatic",
                  "repugnant",
                  "conformists",
                  "deviants",
                  "venerable",
                  "enduring",
                  "fleeting",
                  "decadent",
                  "resilient",
                  "conservational",
                  "wasteful"];

traitsDict = {
  "agrarian": new Trait("Agrarian", 2, ["none"], {"tileResourceFoodMult": 0.15}, ["all"]),
  "thrifty": new Trait("Thrifty", 2, ["none"], {"tileResourceEnergyMult": 0.15}, ["all"]),
  "industrious": new Trait("Industrious", 2, ["none"], {"tileResourceMineralsMult": 0.15}, ["all"]),
  "intelligent": new Trait("Intelligent", 2, ["nerveStapled", "erudite"], {"tileResourceEngineeringResearchMult": 0.1,
                                                            "tileResourcePhysicsResearchMult": 0.1,
                                                            "tileResourceSocietyResearchMult": 0.1}, ["all"]),
  "naturalEngineers": new Trait("Natural Engineers", 1, ["naturalPhysicists", "naturalSociologists", "nerveStapled"], {"tileResourceEngineeringResearchMult": 0.15}, ["all"]),
  "naturalPhysicists": new Trait("Natural Physicists", 1, ["naturalEngineers", "naturalSociologists", "nerveStapled"], {"tileResourcePhysicsResearchMult": 0.15}, ["all"]),
  "naturalSociologists": new Trait("Natural Sociologists", 1, ["naturalPhysicists", "naturalEngineers", "nerveStapled"], {"tileResourceSocietyResearchMult": 0.15}, ["all"]),
  "extremelyAdaptive": new Trait("Extremely Adaptive", 4, ["nonAdaptive", "adaptive", "robust"], {"popEnvironmentTolerance": 0.2}, ["all"]),
  "adaptive": new Trait("Adaptive", 2, ["nonAdaptive", "extremelyAdaptive", "robust"], {"popEnvironmentTolerance": 0.1}, ["all"]),
  "nonAdaptive": new Trait("Non-adaptive", -2, ["adaptive", "extremelyAdaptive", "robust"], {"popEnvironmentTolerance": -0.1}, ["all"]),
  "rapidBreeders": new Trait("Rapid Breeders", 1, ["slowBreeders", "fertile"], {"popGrowthSpeed": 0.15}, ["all"]),
  "slowBreeders": new Trait("Slow Breeders", -1, ["rapidBreeders", "fertile"], {"popGrowthSpeed": -0.15}, ["all"]),
  "talented": new Trait("Talented", 1, ["none"], {"leaderSkillLevels": 0.1}),
  "quickLearners": new Trait("Quick Learners", 1, ["slowLearners"], {"speciesLeaderExpGain": 0.25}, ["all"]),
  "slowLearners": new Trait("Slow Learners", -1, ["quickLearners"], {"speciesLeaderExpGain": -0.25}, ["all"]),
  "veryStrong": new Trait("Very Strong", 3, ["weak", "strong"], {"armyDamageMult": 0.4,
                                                                 "tileResourceMineralsMult": 0.1}, ["all"]),
  "strong": new Trait("Strong", 1, ["weak", "veryStrong"], {"armyDamageMult": 0.2,
                                                            "tileResourceMineralsMult": 0.05}, ["all"]),
  "weak": new Trait("Weak", -1, ["strong", "veryStrong"], {"armyDamageMult": -0.2,
                                                           "tileResourceMineralsMult": -0.05}, ["all"]),
  "nomadic": new Trait("Nomadic", 1, ["sedentary"], {"popMigrationSpeed": 0.5,
                                                     "popResettlementCostMult": -0.25}, ["all"]),
  "sedentary": new Trait("Sedentary", -1, ["nomadic"], {"popMigrationSpeed": -0.5,
                                                        "popResettlementCostMult": 0.25}, ["all"]),
  "communal": new Trait("Communal", 1, ["solitary"], {"popHappiness": 0.05}, ["authoritarian",
                                                                              "fAuthoritarian",
                                                                              "egalitarian",
                                                                              "fEgalitarian",
                                                                              "xenophobe",
                                                                              "fXenophobe",
                                                                              "xenophile",
                                                                              "fXenophile",
                                                                              "materialist",
                                                                              "fMaterialist",
                                                                              "spiritualist",
                                                                              "fSpiritualist",
                                                                              "militarist",
                                                                              "fMilitarist",
                                                                              "pacifist",
                                                                              "fPacifist"]),
  "solitary": new Trait("Solitary", -1, ["communal"], {"popHappiness": -0.05}, ["authoritarian",
                                                                                "fAuthoritarian",
                                                                                "egalitarian",
                                                                                "fEgalitarian",
                                                                                "xenophobe",
                                                                                "fXenophobe",
                                                                                "xenophile",
                                                                                "fXenophile",
                                                                                "materialist",
                                                                                "fMaterialist",
                                                                                "spiritualist",
                                                                                "fSpiritualist",
                                                                                "militarist",
                                                                                "fMilitarist",
                                                                                "pacifist",
                                                                                "fPacifist"]),
  "charismatic": new Trait("Charismatic", 1, ["repugnant"], {"leaderOpinion": 25}, ["all"]),
  "repugnant": new Trait("Repugnant", -1, ["charismatic"], {"leaderOpinion": -25}, ["all"]),
  "conformists": new Trait("Conformists", 2, ["deviants"], {"popGovernmentEthicAttraction": 0.25}, ["authoritarian",
                                                                                                    "fAuthoritarian",
                                                                                                    "egalitarian",
                                                                                                    "fEgalitarian",
                                                                                                    "xenophobe",
                                                                                                    "fXenophobe",
                                                                                                    "xenophile",
                                                                                                    "fXenophile",
                                                                                                    "materialist",
                                                                                                    "fMaterialist",
                                                                                                    "spiritualist",
                                                                                                    "fSpiritualist",
                                                                                                    "militarist",
                                                                                                    "fMilitarist",
                                                                                                    "pacifist",
                                                                                                    "fPacifist"]),
    "deviants": new Trait("Deviants", -1, ["conformists"], {"popGovernmentEthicAttraction": -0.15}, ["authoritarian",
                                                                                                     "fAuthoritarian",
                                                                                                     "egalitarian",
                                                                                                     "fEgalitarian",
                                                                                                     "xenophobe",
                                                                                                     "fXenophobe",
                                                                                                     "xenophile",
                                                                                                     "fXenophile",
                                                                                                     "materialist",
                                                                                                     "fMaterialist",
                                                                                                     "spiritualist",
                                                                                                     "fSpiritualist",
                                                                                                     "militarist",
                                                                                                     "fMilitarist",
                                                                                                     "pacifist",
                                                                                                     "fPacifist"]),
    "venerable": new Trait("Venerable", 4, ["enduring", "fleeting"], {"leaderAge": 75}, ["all"]),
    "enduring": new Trait("Enduring", 1, ["venerable", "fleeting"], {"leaderAge": 15}, ["all"]),
    "fleeting": new Trait("Fleeting", -1, ["enduring", "enduring"], {"leaderAge": -10}, ["all"]),
    "decadent": new Trait("Decadent", -1, ["none"], {"popEffWoSlaves": -0.1}, ["authoritarian",
                                                                               "fAuthoritarian",
                                                                               "xenophobe",
                                                                               "fXenophobe"]),
    "resilient": new Trait("Resilient", 1, ["none"], {"garrisonHealth": 1.0,
                                                      "popFortificationDefense": 0.5}, ["all"]),
    "conservational": new Trait("Conservational", 1, ["wasteful"], {"popConsumerGoodsMult": -0.2}, ["all"]),
    "wasteful": new Trait("Wasteful", 1, ["conservational"], {"popConsumerGoodsMult": 0.2}, ["all"]),
};