class Trait {
  constructor(name, cost, opposites, modifiers, allowedEthics) {
    this.name = name;
    this.cost = cost;
    this.opposites = opposites;
    this.modifiers = modifiers;
    this.allowedEthics = allowedEthics;
  }
}

var traitsList = [
  "Agrarian", 
  "Thrifty", 
  "Industrious", 
  "Intelligent", 
  "Natural Engineers", 
  "Natural Physicists", 
  "Natural Sociologists",
  "Extremely Adaptive",
  "Adaptive",
  "Non-adaptive",
  "Rapid Breeders",
  "Slow Breeders",
  "Talented",
  "Quick Learners",
  "Slow Learners",
  "Very Strong",
  "Strong",
  "Weak",
  "Nomadic",
  "Nomadic",
  "Communal",
  "Solitary",
  "Charismatic",
  "Repugnant",
  "Conformists",
  "Deviants",
  "Venerable",
  "Enduring",
  "Fleeting",
  "Decadent",
  "Resilient",
  "Conservational",
  "Wasteful"
];

traitsDict = {
  "Agrarian": new Trait("Agrarian", 2, ["none"], {"tileResourceFoodMult": 0.15}, ["all"]),
  "Thrifty": new Trait("Thrifty", 2, ["none"], {"tileResourceEnergyMult": 0.15}, ["all"]),
  "Industrious": new Trait("Industrious", 2, ["none"], {"tileResourceMineralsMult": 0.15}, ["all"]),
  "Intelligent": new Trait("Intelligent", 2, ["nerveStapled", "erudite"], {"tileResourceEngineeringResearchMult": 0.1,
                                                            "tileResourcePhysicsResearchMult": 0.1,
                                                            "tileResourceSocietyResearchMult": 0.1}, ["all"]),
  "Natural Engineers": new Trait("Natural Engineers", 1, ["Natural Physicists", "Natural Sociologists", "nerveStapled"], {"tileResourceEngineeringResearchMult": 0.15}, ["all"]),
  "Natural Physicists": new Trait("Natural Physicists", 1, ["Natural Engineers", "Natural Sociologists", "nerveStapled"], {"tileResourcePhysicsResearchMult": 0.15}, ["all"]),
  "Natural Sociologists": new Trait("Natural Sociologists", 1, ["Natural Physicists", "Natural Engineers", "nerveStapled"], {"tileResourceSocietyResearchMult": 0.15}, ["all"]),
  "Extremely Adaptive": new Trait("Extremely Adaptive", 4, ["Non-adaptive", "Adaptive", "robust"], {"popEnvironmentTolerance": 0.2}, ["all"]),
  "Adaptive": new Trait("Adaptive", 2, ["Non-adaptive", "Extremely Adaptive", "robust"], {"popEnvironmentTolerance": 0.1}, ["all"]),
  "Non-adaptive": new Trait("Non-adaptive", -2, ["Adaptive", "Extremely Adaptive", "robust"], {"popEnvironmentTolerance": -0.1}, ["all"]),
  "Rapid Breeders": new Trait("Rapid Breeders", 1, ["Slow Breeders", "fertile"], {"popGrowthSpeed": 0.15}, ["all"]),
  "Slow Breeders": new Trait("Slow Breeders", -1, ["Rapid Breeders", "fertile"], {"popGrowthSpeed": -0.15}, ["all"]),
  "Talented": new Trait("Talented", 1, ["none"], {"leaderSkillLevels": 0.1}, ["all"]),
  "Quick Learners": new Trait("Quick Learners", 1, ["Slow Learners"], {"speciesLeaderExpGain": 0.25}, ["all"]),
  "Slow Learners": new Trait("Slow Learners", -1, ["Quick Learners"], {"speciesLeaderExpGain": -0.25}, ["all"]),
  "Very Strong": new Trait("Very Strong", 3, ["Weak", "Strong"], {"armyDamageMult": 0.4,
                                                                 "tileResourceMineralsMult": 0.1}, ["all"]),
  "Strong": new Trait("Strong", 1, ["Weak", "Very Strong"], {"armyDamageMult": 0.2,
                                                            "tileResourceMineralsMult": 0.05}, ["all"]),
  "Weak": new Trait("Weak", -1, ["Strong", "Very Strong"], {"armyDamageMult": -0.2,
                                                           "tileResourceMineralsMult": -0.05}, ["all"]),
  "Nomadic": new Trait("Nomadic", 1, ["Sedentary"], {"popMigrationSpeed": 0.5,
                                                     "popResettlementCostMult": -0.25}, ["all"]),
  "Sedentary": new Trait("Sedentary", -1, ["Nomadic"], {"popMigrationSpeed": -0.5,
                                                        "popResettlementCostMult": 0.25}, ["all"]),
  "Communal": new Trait("Communal", 1, ["Solitary"], {"popHappiness": 0.05}, ["Authoritarian",
                                                                              "Fanatic Authoritarian",
                                                                              "Egalitarian",
                                                                              "Fanatic Egalitarian",
                                                                              "Xenophobe",
                                                                              "Fanatic Xenophobe",
                                                                              "Xenophile",
                                                                              "Fanatic Xenophile",
                                                                              "Materialist",
                                                                              "Fanatic Materialist",
                                                                              "Spiritualist",
                                                                              "Fanatic Spiritualist",
                                                                              "Militarist",
                                                                              "Fanatic Militarist",
                                                                              "Pacifist",
                                                                              "Fanatic Pacifist"]),
  "Solitary": new Trait("Solitary", -1, ["Communal"], {"popHappiness": -0.05}, ["Authoritarian",
                                                                                "Fanatic Authoritarian",
                                                                                "Egalitarian",
                                                                                "Fanatic Egalitarian",
                                                                                "Xenophobe",
                                                                                "Fanatic Xenophobe",
                                                                                "Xenophile",
                                                                                "Fanatic Xenophile",
                                                                                "Materialist",
                                                                                "Fanatic Materialist",
                                                                                "Spiritualist",
                                                                                "Fanatic Spiritualist",
                                                                                "Militarist",
                                                                                "Fanatic Militarist",
                                                                                "Pacifist",
                                                                                "Fanatic Pacifist"]),
  "Charismatic": new Trait("Charismatic", 1, ["Repugnant"], {"leaderOpinion": 25}, ["all"]),
  "Repugnant": new Trait("Repugnant", -1, ["Charismatic"], {"leaderOpinion": -25}, ["all"]),
  "Conformists": new Trait("Conformists", 2, ["Deviants"], {"popGovernmentEthicAttraction": 0.25}, ["Authoritarian",
                                                                                                    "Fanatic Authoritarian",
                                                                                                    "Egalitarian",
                                                                                                    "Fanatic Egalitarian",
                                                                                                    "Xenophobe",
                                                                                                    "Fanatic Xenophobe",
                                                                                                    "Xenophile",
                                                                                                    "Fanatic Xenophile",
                                                                                                    "Materialist",
                                                                                                    "Fanatic Materialist",
                                                                                                    "Spiritualist",
                                                                                                    "Fanatic Spiritualist",
                                                                                                    "Militarist",
                                                                                                    "Fanatic Militarist",
                                                                                                    "Pacifist",
                                                                                                    "Fanatic Pacifist"]),
    "Deviants": new Trait("Deviants", -1, ["Conformists"], {"popGovernmentEthicAttraction": -0.15}, ["Authoritarian",
                                                                                                     "Fanatic Authoritarian",
                                                                                                     "Egalitarian",
                                                                                                     "Fanatic Egalitarian",
                                                                                                     "Xenophobe",
                                                                                                     "Fanatic Xenophobe",
                                                                                                     "Xenophile",
                                                                                                     "Fanatic Xenophile",
                                                                                                     "Materialist",
                                                                                                     "Fanatic Materialist",
                                                                                                     "Spiritualist",
                                                                                                     "Fanatic Spiritualist",
                                                                                                     "Militarist",
                                                                                                     "Fanatic Militarist",
                                                                                                     "Pacifist",
                                                                                                     "Fanatic Pacifist"]),
    "Venerable": new Trait("Venerable", 4, ["Enduring", "Fleeting"], {"leaderAge": 75}, ["all"]),
    "Enduring": new Trait("Enduring", 1, ["Venerable", "Fleeting"], {"leaderAge": 15}, ["all"]),
    "Fleeting": new Trait("Fleeting", -1, ["Venerable", "Enduring"], {"leaderAge": -10}, ["all"]),
    "Decadent": new Trait("Decadent", -1, ["none"], {"popEffWoSlaves": -0.1}, ["Authoritarian",
                                                                               "Fanatic Authoritarian",
                                                                               "Xenophobe",
                                                                               "Fanatic Xenophobe"]),
    "Resilient": new Trait("Resilient", 1, ["none"], {"garrisonHealth": 1.0,
                                                      "popFortificationDefense": 0.5}, ["all"]),
    "Conservational": new Trait("Conservational", 1, ["Wasteful"], {"popConsumerGoodsMult": -0.2}, ["all"]),
    "Wasteful": new Trait("Wasteful", 1, ["Conservational"], {"popConsumerGoodsMult": 0.2}, ["all"]),
};